### ISSUE TITLE
Bio and Materials URL not displaying in talk 

### ISSUE THREAD

**Issue by zkamvar** [rstudio/rstudio-conf-2022-program#28]
I updated my talk markdown in #14 to fix some formatting and add a URL for materials, but now nothing shows up for bio or materials: https://rstudioconf2022.sched.com/event/866f939b8e168ae0c191421e7a58bf86

**Comment by gadenbuie** [comment]
Thanks for letting us know. Materials aren't published anywhere yet. I'll look into the issue with your bio.
